-- Seed the brand→generic alias dictionary with common Part D brands so the
-- resolution ladder hits rung 2 (alias) without ever needing the LLM.
-- Keys are normalized molecule keys (see @rxsr/core drugs/resolution).
INSERT INTO "drug_aliases" ("alias", "generic_name", "is_combination", "components", "source") VALUES
  ('zetia', 'ezetimibe', false, '{}', 'seed'),
  ('eliquis', 'apixaban', false, '{}', 'seed'),
  ('xarelto', 'rivaroxaban', false, '{}', 'seed'),
  ('jardiance', 'empagliflozin', false, '{}', 'seed'),
  ('farxiga', 'dapagliflozin', false, '{}', 'seed'),
  ('januvia', 'sitagliptin', false, '{}', 'seed'),
  ('ozempic', 'semaglutide', false, '{}', 'seed'),
  ('rybelsus', 'semaglutide', false, '{}', 'seed'),
  ('trulicity', 'dulaglutide', false, '{}', 'seed'),
  ('lantus', 'insulin glargine', false, '{}', 'seed'),
  ('basaglar', 'insulin glargine', false, '{}', 'seed'),
  ('levemir', 'insulin detemir', false, '{}', 'seed'),
  ('crestor', 'rosuvastatin', false, '{}', 'seed'),
  ('lipitor', 'atorvastatin', false, '{}', 'seed'),
  ('zocor', 'simvastatin', false, '{}', 'seed'),
  ('plavix', 'clopidogrel', false, '{}', 'seed'),
  ('synthroid', 'levothyroxine', false, '{}', 'seed'),
  ('nexium', 'esomeprazole', false, '{}', 'seed'),
  ('prilosec', 'omeprazole', false, '{}', 'seed'),
  ('protonix', 'pantoprazole', false, '{}', 'seed'),
  ('zoloft', 'sertraline', false, '{}', 'seed'),
  ('lexapro', 'escitalopram', false, '{}', 'seed'),
  ('cymbalta', 'duloxetine', false, '{}', 'seed'),
  ('norvasc', 'amlodipine', false, '{}', 'seed'),
  ('cozaar', 'losartan', false, '{}', 'seed'),
  ('diovan', 'valsartan', false, '{}', 'seed'),
  ('zestril', 'lisinopril', false, '{}', 'seed'),
  ('prinivil', 'lisinopril', false, '{}', 'seed'),
  ('coumadin', 'warfarin', false, '{}', 'seed'),
  ('glucophage', 'metformin', false, '{}', 'seed'),
  ('lasix', 'furosemide', false, '{}', 'seed'),
  ('coreg', 'carvedilol', false, '{}', 'seed'),
  ('singulair', 'montelukast', false, '{}', 'seed'),
  ('flomax', 'tamsulosin', false, '{}', 'seed'),
  ('proscar', 'finasteride', false, '{}', 'seed'),
  ('celebrex', 'celecoxib', false, '{}', 'seed'),
  ('neurontin', 'gabapentin', false, '{}', 'seed'),
  ('lyrica', 'pregabalin', false, '{}', 'seed'),
  ('ambien', 'zolpidem', false, '{}', 'seed'),
  ('spiriva', 'tiotropium', false, '{}', 'seed'),
  ('plaquenil', 'hydroxychloroquine', false, '{}', 'seed'),
  ('zyloprim', 'allopurinol', false, '{}', 'seed'),
  ('flexeril', 'cyclobenzaprine', false, '{}', 'seed'),
  ('aricept', 'donepezil', false, '{}', 'seed'),
  ('namenda', 'memantine', false, '{}', 'seed'),
  ('eloctate', 'efmoroctocog alfa', false, '{}', 'seed'),
  ('vytorin', 'ezetimibe simvastatin', true, '{ezetimibe,simvastatin}', 'seed'),
  ('hyzaar', 'losartan hydrochlorothiazide', true, '{losartan,hydrochlorothiazide}', 'seed'),
  ('entresto', 'sacubitril valsartan', true, '{sacubitril,valsartan}', 'seed'),
  ('advair', 'fluticasone salmeterol', true, '{fluticasone,salmeterol}', 'seed'),
  ('symbicort', 'budesonide formoterol', true, '{budesonide,formoterol}', 'seed')
ON CONFLICT ("alias") DO NOTHING;
